baseURL = "https://lam0helloworld.github.io/lam-temp-site/"
languageCode = "zh-cn"
title = "Lam的多重宇宙"

[params]
  author = "Lam"
  description = "记录一些输入和输出，以及别的"

  defaultTheme = "light"

  profileMode:
    enabled = true
    title = "Lam的多重宇宙"
    subtitle = "知识探索者 / 自学者 / 日常记录者<br>(其实我是一个多维存在体)"
    imageUrl = "/images/avatar.jpg"
    imageWidth = 200
    imageHeight = 200

  socialIcons = []

[menu]
  [[menu.main]]
    name = "关于我"
    url = "/about/"
  [[menu.main]]
    name = "专业·输出"
    url = "/professional/"
  [[menu.main]]
    name = "业余·输入"
    url = "/selfstudy/"
  [[menu.main]]
    name = "日常记录"
    url = "/daily/"
  [[menu.main]]
    name = "联系我"
    url = "/contact/"
