baseURL = "https://lam0helloworld.github.io/lam-temp-site/"   # 临时 URL 测试
languageCode = "zh-cn"
title = "Lam的多重宇宙"

theme = "hugo-PaperMod"   # 注意大小写匹配仓库名

[params]
  author = "Lam"
  description = "记录一些输入和输出，以及别的"

  defaultTheme = "light"   # 强制白色/亮色

  homeInfoParams:
    Title = "Lam的多重宇宙"
    Content = "知识探索者 / 自学者 / 日常记录者<br>(其实我是一个多维存在体)"

  avatarurl = "/images/avatar.jpg"   # 上传后路径

  socialIcons = []   # 去掉社交图标

[menu]
  [[menu.main]]
    name = "关于我"
    url = "/about/"
  [[menu.main]]
    name = "专业·输出"
    url = "/professional/"
  [[menu.main]]
    name = "业余·输入"
    url = "/selfstudy/"
  [[menu.main]]
    name = "日常记录"
    url = "/daily/"
  [[menu.main]]
    name = "联系我"
    url = "/contact/"
